### ISSUE TITLE
Kanban Board Review

### ISSUE THREAD

**Issue by Chimoneg27** [Chimoneg27/Module-2-Capstone-Kanban-Board#21]
Hello Code Reviewer, me and @ismayito are a group of 2. The link to our Kanban board is: https://github.com/Chimoneg27/Module-2-Capstone-Kanban-Board/projects/3.

**Comment by ridwanediallo** [comment]
# Changes Required ♻️
## Hi :wave: team, 
![AlmostThereReachGIF](https://user-images.githubusercontent.com/55918904/191301799-36d07166-0e35-4582-a231-7a2d780f7783.gif)

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!

## (Highlights) Good Points: :+1:
- You documented your work professionally. ✔
- Project created based on the template. ✔
- The expected number of cards has been added and all cards have descriptions. ✔


## Required Changes ♻️

- [ ] Congratulations for finishing the project's 95% of the requirements 👏. So let's make sure the job is finished to a perfect standard by making sure every card has a **assignee**. 👌 It indicates that the jobs should be evenly distributed among the team members because doing so will facilitate simpler teamwork in addition to being one of the requirements. Everyone will benefit from knowing which tasks to concentrate on if this is done. 😊
**When a card has a assignee, it's going to look like this**  :point_down: 
![Screenshot from 2023-09-04 13-37-01](https://github.com/Chimoneg27/Module-2-Capstone-Kanban-Board/assets/89228743/39b9c338-d6ce-42f0-b011-5bab335d5805)

### Misssing requirement :point_down: 

![Screenshot from 2023-09-04 13-18-45](https://github.com/Chimoneg27/Module-2-Capstone-Kanban-Board/assets/89228743/b994a6a8-70e5-4db6-a0f2-40fb93514927)


## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Comment by DammyShittu** [comment]
Hi @Chimoneg27 and @ismayito,

## APPROVED 🟢

## Highlights
✔️ Assigned tasks

Great implementation of all the requirements in this milestone. 👏 

_You have done an amazing job 👍_

Your project is complete!  There is nothing else to say other than... it's time to merge it. :shipit: 

Congratulations! 🎉 

## CHEERS AND HAPPY CODING!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._
